#!/bin/bash

echo ${SPARK_SUBMIT_ARGS} ${SPARK_APPLICATION_MAIN_CLASS}  ${SPARK_APPLICATION_SUPPORTING_JARS_LOCATION} \
    ${SPARK_APPLICATION_JAR_LOCATION} ${SPARK_APPLICATION_ARGS}

/spark/bin/spark-submit \
    ${SPARK_APPLICATION_MAIN_CLASS} \
    ${SPARK_SUBMIT_ARGS} \
    ${SPARK_APPLICATION_SUPPORTING_JARS_LOCATION} \
    ${SPARK_APPLICATION_JAR_LOCATION} ${SPARK_APPLICATION_ARGS}